データベース課題3のPR
kamdam13/quelcode-db pull request #3
Opened 2020-06-18 06:07 UTC by kamdam13

# db/db-challenge3/ 下の各課題についてレビューお願いします！
## やったこと
- 001 ~ 005の各問題についてSQLを作成し、実行結果のスクリーンショットを撮影しました、

2020-06-18 06:22 UTC, piasoratech reviewed
No005まで確認しました！OKです！

2020-06-18 15:17 UTC, kamdam13 commented
# PRを更新しました
## やったこと
- 006 ~ 010までの各問題について、SQLを作成しました

2020-06-19 02:32 UTC, piasoratech requested changes
実行時のキャプチャがないのでキャプチャをとって再提出してください。

2020-06-19 02:43 UTC, kamdam13 commented
# PRを更新しました
## やったこと
- 006 ~ 010 までのSQLの実行結果のキャプチャを追加しました

2020-06-19 03:15 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-19 03:15 UTC, piasoratech commented on db/db-challenge3/db-010/db-010.sql
> +,	u.id
今回の要件では`users`テーブルの`id`を表示するように書いていません。

2020-06-19 03:18 UTC, kamdam13 commented
# PRを更新しました
## やったこと
- db-010にて、不要な列を選択してしまっているところを修正しました

2020-06-19 03:53 UTC, piasoratech requested changes
キャプチャ画像の差し替えも行ってください

2020-06-19 04:08 UTC, kamdam13 commented
# PRを更新しました
## やったこと
- db-010.pngを更新しました

2020-06-19 05:14 UTC, piasoratech reviewed
OKです
次に進みましょう！

2020-06-19 08:21 UTC, kamdam13 commented
# PRを更新しました
## やったこと
- 011 ~ 014の各問題について、SQLを作成しました
- 011 ~ 014のSQLの実行結果のスクリーンショットを作成しました

2020-06-19 08:34 UTC, piasoratech approved these changes
OKです！
お疲れ様でした！

2020-06-20 08:41 UTC, merged